### ISSUE TITLE
Where is the build task ?

### ISSUE THREAD

**Issue by fmichaud** [cmackay/ionic-todos#1]
Hi,

The task used to build application seems missing. Could you push it ?

Thank you.

**Comment by cmackay** [comment]
Good question. I haven't looked at this in a while and it seems I don't have a build task anywhere. Seems like that would be an important task to have :) I did just recently created another project which has a lot more functionality to it if you want to check it out.  https://github.com/cmackay/hybrid-boilerplate
It uses webpack instead of browserify. If you check it out and have any feedback let me know. Also I will look into adding a build task to this project. I will leave this issue open until it is added.

Thanks,

-Craig

**Comment by cmackay** [comment]
also if you want to run the build you can always run the watch task and then exit by using ctrl-c and then run cordova build
